apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: kpack-builder
spec:
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: github
          params:
            - name: secretRef
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
            - name: "addChangedFiles"
              value:
                enabled: true
        - name: "only when PRs are opened"
          ref:
            name: cel
          params:
            - name: filter
              value: "body.action in ['opened', 'synchronize', 'reopened']"
        - name: "only when php project was changed"
          ref:
            name: cel
          params:
          - name: filter
            value: extensions.changed_files.matches('projects/php/')
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-php-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers
