apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - build-template.yaml
  - event-listener.yaml
  - pr-binding.yaml
  - rbac.yaml
  - secret.yaml
  - https://api.hub.tekton.dev/v1/resource/tekton/task/kubernetes-actions/0.2/raw
namespace: kpack-builder
