apiVersion: v1
kind: Secret
metadata:
    name: github-secret
    namespace: kpack-builder
stringData:
    secretToken: ENC[AES256_GCM,data:pmK5NlH6EDS8VE7VwpiB7FQCoFOS/SHvv9IlTd8k,iv:jnBgo9ldbAVky2aM4L3A2JVQXvIscIJrrw5tOsj5bqs=,tag:y3PtSaP/F+20O+BtitAeRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-08T12:56:41Z"
    mac: ENC[AES256_GCM,data:PQm8edh0O+KEUOf291+VH4uctTILsAknO9NdKm0a7p2F+eQzb/yMDw28VeFQzoaMi0YsV3md4QOJ8MCsccmPN0QKkcLjbXPo+MIj3tMuoC57kWdvvGO8TykyNqqwtTaT+GVbil4wJkoDahWOOyern/m6N3bXXa8m4W4nrLNK9bs=,iv:4R4yWkpX0a327BmXYmgAP0vc1ATgTwQrML0seMpTvLk=,tag:bDGgFw2RoSXduN8XRoTd0A==,type:str]
    pgp:
        - created_at: "2023-04-08T12:56:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6RoZz/qT7RNAQ//TbSpgzuIrYgIkNeC3TIp2yMiICVRD0OEsQmzhNi2n4F/
            sqGaVzUg/ukxX+z8aSqVsXldA92zMs/jQfhNW3RSqQ33EiBCO1nR47vrIpEv35Nf
            wi48+RqRwnRj7XsTVUd04K4IMYO3QA0uqv+1r8Occ+F0Z9C3OVSJhVg4Zk6Z4wTc
            f8Qz94e/3qcmwmc3xcyZuTlZVMQD5rCxOENs05kzREsQ8y8zIKW7uqZYRwmvBRRu
            nsevDK2fM8UvOrUU+JfgFuqQ3+U/P+wDjmyNE+p8sBlB2wPXFMnGW7dYcEAAoMO0
            Du4kPTRQAZFru0hgxB6hFT8n67QVsHDI3M75lYV8ow777O9AWPIoKRa7eIQJKwmm
            1xiTqyaZyFwGcE0RI39RpeWQDjJwnOsyEGsKh4sjIKCepTuXw+705LaMHI5CsQIa
            s8s2dPqoda98RCWE0stNsboo6ff75eSaUuO6FMyLb+7PN26ACZR6dvYT/fVbuJSH
            JN1yKhbfb8yfiaAaBO0QOQ8OytftYOpsuFqxdYmEA5sf5e78HtGIVND2gutZadS0
            aiU02qxHHVeyFcjjHVhOlVH9j/xnsVwQpfs3ow1Oiuo3l79F4iNzIUIXJRC9zMjh
            G1XLt9auzweZocb3FFzZFE8JKASqYV0x/ZsfISOQfbf+i86WUVZTzwLQ5TwlT5XU
            aAEJAhA/Yfxa4u6+WssTGOi39TUHywygqWYhASNXakNkfxaPkrIbyzEWXNWe2tDU
            Atn91j+3keazWdwN6WBl0GZT7Sx5lFcsvMxvj1+uIvhS7fcBDUaAVNzfeZHRKBu8
            qEgV3i1K/QpT
            =9UFi
            -----END PGP MESSAGE-----
          fp: B69408BAAC547B2266B20CD23F626B3848432B5F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
