apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: go
  namespace: kpack-builder
spec:
  tag: ghcr.io/anasinnyk/go
  builder:
    kind: ClusterBuilder
    name: all-builders
  serviceAccountName: kpack
  source:
    git:
      url: https://github.com/anasinnyk/php-go-node-rust-monorepo-example.git
      revision: main
    subPath: projects/go
