apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: php
  namespace: kpack-builder
spec:
  tag: ghcr.io/anasinnyk/php
  builder:
    kind: ClusterBuilder
    name: all-builders
  serviceAccountName: kpack
  source:
    git:
      url: https://github.com/anasinnyk/php-go-node-rust-monorepo-example.git
      revision: main
    subPath: projects/php
  build:
    env:
      - name: BP_PHP_WEB_DIR
        value: public
      - name: BP_PHP_SERVER
        value: nginx
      - name: BP_DOTENV_SUFFIX
        value: production
      - name: PORT
        value: "8080"
