apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: all-builders
spec:
  tag: ghcr.io/anasinnyk/buildpacks-builder
  stack:
    name: stack
    kind: ClusterStack
  store:
    name: store
    kind: ClusterStore
  serviceAccountRef:
    name: kpack
    namespace: kpack-builder
  order:
  - group:
    - id: paketo-community/rust
    - id: anasinnyk/dotenv
  - group:
    - id: paketo-buildpacks/nodejs
    - id: anasinnyk/dotenv
  - group:
    - id: paketo-buildpacks/php
    - id: anasinnyk/dotenv
  - group:
    - id: paketo-buildpacks/go
    - id: anasinnyk/dotenv
