apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack
  namespace: kpack-builder
subjects:
- kind: ServiceAccount
  name: kpack
roleRef:
  name: access-to-kpack
  kind: Role
